[tool.poetry]
name = "csdocgen"
version = "0.1.0"
description = "Generate XML documentation for C# classes using offline AI model"
authors = ["Maciek <maciek@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
torch = {version = "^2.2.1+cpu", source = "pytorch_cpu"}
transformers = "^4.40.0"
click = "^8.1.7"

[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.scripts]
csdocgen = "csdocgen.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
